# Generated by Django 3.2 on 2025-04-23 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Without Payment'), (2, 'With Payment')], unique=True)),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('price', models.IntegerField()),
                ('api_keys', models.CharField(max_length=255, null=True)),
                ('plan_img', models.ImageField(blank=True, upload_to='Plan Images', verbose_name='Plan Images')),
                ('is_free', models.BooleanField(default=False)),
                ('duration', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('appointment_point', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='price.priceplan')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('subscription_from', models.DateField(null=True, verbose_name='Subscription From')),
                ('subscription_to', models.DateField(null=True, verbose_name='Subscription To')),
                ('stripeCustomerId', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Customer Id')),
                ('stripeSubscriptionId', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Subscription Id')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expire', 'Expire'), ('cancel', 'Cancel'), ('pending', 'Pending')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='price.priceplan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.AddConstraint(
            model_name='priceplan',
            constraint=models.UniqueConstraint(fields=('title', 'duration', 'activity'), name='unique_title_duration'),
        ),
    ]
