# Generated by Django 3.2 on 2025-04-26 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('inside_china', 'Inside China'), ('outside_china', 'Outside China')], max_length=20, verbose_name='Region')),
                ('payment_method', models.CharField(max_length=20, verbose_name='Payment Method')),
            ],
        ),
        migrations.DeleteModel(
            name='MeetingLink',
        ),
        migrations.AlterModelOptions(
            name='priceplan',
            options={'verbose_name_plural': 'Price Plans'},
        ),
        migrations.RemoveConstraint(
            model_name='priceplan',
            name='unique_title_duration',
        ),
        migrations.RenameField(
            model_name='priceplan',
            old_name='appointment_point',
            new_name='credits',
        ),
        migrations.RemoveField(
            model_name='priceplan',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='priceplan',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='priceplan',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='priceplan',
            name='plan_img',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='stripeCustomerId',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='stripeSubscriptionId',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='subscription_from',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='subscription_to',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='inserted_on',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='priceplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceplan',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
