# Generated by Django 3.2 on 2025-04-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20250426_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceplan',
            name='inside_china',
            field=models.BooleanField(default=True),
        ),
    ]
