# Generated by Django 3.2 on 2025-04-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_auto_20250426_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
