# Generated by Django 3.2 on 2025-04-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_alter_priceplan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceplan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
