# Generated by Django 3.2 on 2025-04-23 15:01

import core.models.profile
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('requisitions', models.TextField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('is_accept', models.BooleanField(default=False)),
                ('is_agree', models.BooleanField(default=False)),
                ('is_info', models.BooleanField(default=False)),
                ('is_tax_info', models.BooleanField(default=False)),
                ('is_file', models.BooleanField(default=False)),
                ('is_payment', models.BooleanField(default=False)),
                ('is_bank', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.profile.media_upload_path)),
            ],
        ),
    ]
